### ISSUE TITLE
Hard to see in auto-complement string color

### ISSUE THREAD

**Issue by WindSoilder** [icewind/everforest.iterm2#1]
Hi, thanks for your awesome port, but I get an issue for auto-complement feature in `fish` shell.  Here is my screenshot:
![截屏2021-12-31 上午11 55 29](https://user-images.githubusercontent.com/22256154/147802412-bdcc6bf1-4b09-4917-80ec-5808c835a968.png)

If you zoom in and look carefully, you may see ~/tmp there.  But it's too hard to read...

Theme: Everforest_hard_dark

It looks much better in vscode intergrated terminal:
![图片](https://user-images.githubusercontent.com/22256154/147802517-64b086dc-a2f2-45b7-a905-adc82539fb5f.png)

**Comment by icewind** [comment]
Hi! Thanks for a report. I'll take a look.

**Comment by icewind** [comment]
Replaced autosuggestion color. Please check and feel free to reopen if it won't help.
